theme: jekyll-theme-architect
title: Tutoriais de Econometria
author: Davi Moura
email: davipnm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Qualquer dúvida pode entrar em contato comigo por email!
# social links
twitter_username: baidavim # DO NOT include the @ character, or else the build will fail!
github_username:  baianoix # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
